rule("graphviz")
    set_extensions(".dot", ".gv")
    on_load(function (target)
        target:set("targetdir", path.join("build", "asset"))
        os.mkdir(target:targetdir())
        target:set("kind", "object")
    end)
    on_build_file(function (target, sourcefile, opt)
        import("lib.detect.find_tool")
        import("core.project.depend")
        import("utils.progress")
        local dot = assert(find_tool("dot", {check="-V"}), "dot not found!")
        os.vrunv(dot.program, {"-Tpng", "-o", path.join(target:targetdir(), target:name() .. ".png"), sourcefile})
        progress.show(opt.progress, "building %s.png", target:name())
    end)
    on_link(function (target)
    end)
rule_end()

rule("direct_image")
    set_extensions(".png", ".jpg", ".jpeg", ".pdf")
    on_load(function (target)
        target:set("targetdir", path.join("build", "asset"))
        os.mkdir(target:targetdir())
        target:set("kind", "object")
    end)
    on_build_file(function (target, sourcefile, opt)
        import("utils.progress")
        os.cp(sourcefile, target:targetdir())
        progress.show(opt.progress, "moving %s", sourcefile)
    end)
rule_end()

rule("figure")
    add_deps("graphviz", "direct_image")
rule_end()