rule("json_table")
    set_extensions(".json")
    on_load(function (target)
        target:set("targetdir", path.join("build", "asset"))
        os.mkdir(target:targetdir())
        target:set("kind", "object")
    end)
    on_build_file(function (target,sourcefile, opt)
        import("lib.detect.find_tool")
        import("core.project.depend")
        import("utils.progress")
        local py = assert(find_tool("python", {check="--version"}), "python not found!")
        local ofile = path.join(target:targetdir(), target:name() .. ".tex")
        os.vrunv(py.program, {"doc/script/json2tex.py", "--json", sourcefile, "--target", ofile})
        progress.show(opt.progress, "building json2tex %s", sourcefile)
    end)
rule_end()

rule("table")
    add_deps("json_table")
rule_end()