\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{arxiv_art/arxiv_art}[2024/04/15 sailing-innocent]
\LoadClass{article}

\RequirePackage{arxiv_art/arxiv}
\RequirePackage[utf8]{inputenc} 
\RequirePackage[T1]{fontenc}
\RequirePackage{hyperref}
\RequirePackage{url}
\RequirePackage{booktabs}
\RequirePackage{amsfonts}
\RequirePackage{amsmath}

\RequirePackage{nicefrac}
\RequirePackage{microtype}
\RequirePackage{cleveref}
\RequirePackage{lipsum}
\RequirePackage{graphicx}
% \RequirePackage{natbib}
\RequirePackage{doi}
\RequirePackage{subcaption}

\RequirePackage{tikz}
\usetikzlibrary{shapes.symbols}	% 稍后定义 hint 环境所需
\usetikzlibrary{3d, math}
\RequirePackage{pgfplots}
\RequirePackage{pgfplotstable}

